version: "3.7"
services:
  redis:
    image: "redis:7.0.0-alpine"
    ports:
      - "6379:6379"
    environment:
      - REDIS_REPLICATION_MODE=master
    volumes:
      - /home/redis_dump:/data
    command:
      - 'redis-server'
      - '--loglevel ${REDIS_LOGLEVEL:-warning}'
      - '--save 900 1'
      - '--save 300 10'
      - '--save 60 10000'
      - '--maxmemory ${REDIS_MAXMEM:-50mb}'
      - '--maxmemory-policy ${REDIS_POLICY:-noeviction}'
  service:
    build:
      dockerfile: service.Dockerfile
    ports:
      - "8888:8888"
    env_file:
      - dev.env
    restart: always
    depends_on:
      - redis
  cron:
    build:
      dockerfile: cron.Dockerfile
    env_file:
      - dev.env
    ports:
      - "8889:8889"
    restart: always
    depends_on:
      - redis
volumes:
  redis:
